{% set version = "2.1.5" %}

package:
  name: cf-units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf-units/cf-units-{{ version }}.tar.gz
  sha256: d43381d3ee4e3b01ceb29050ea9b5e1bba3bb28d9d5846dff71870162cbc5c33

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    # It isn't clear that this really is needed, but it is listed in setup.py.
    - pytest-runner
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://scitools.org.uk/cf-units/docs/latest/
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
