{% set name = "cf-units" %}
{% set version = "3.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/cf_units/cf_units-{{ version }}.tar.gz
  sha256: 84339f582994ae32ca5c472075c1e603a89f6c6f5a96cc1031bb5da700a14f3a

build:
  number: 1
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    - setuptools
    - setuptools-scm
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime >=1.5.2
    - jinja2

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://cf-units.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units of measure as required by the Climate and Forecast (CF) Metadata Conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
    - pp-mo
