{% set version = "2.1.4" %}

package:
  name: cf-units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf-units/cf-units-{{ version }}.tar.gz
  sha256: 25f81ad994af30713ee8f5ef18ffddd83c6ec1ac308e1bd89d45de9d2e0f1c31

build:
  number: 1
  skip: true  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    # It isn't clear that this really is needed, but it is listed in setup.py.
    - pytest-runner
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*  # [py3k]
    - six

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units                                   # [not (win and py2k)]
      # On win py2 we are getting an unexpected test failure. See also
      # https://github.com/SciTools/cf-units/issues/148.
    - pytest --pyargs cf_units -k="-test_read_xml_invalid_path"  # [win and py2k]

about:
  home: https://scitools.org.uk/cf-units/docs/latest/
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
