{% set version = "2.0.1" %}

package:
  name: cf_units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf_units/cf_units-{{ version }}.tar.gz
  sha256: aeb4978c11518bcb2516c1cf7beb053d1be0cd8e2349a07ad78094f63a2837f4

build:
  number: 1002

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - udunits2 2.2.25  # [win and py2k]
    - udunits2 >=2.2.26,<2.3  # [not (win and py2k)]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - udunits2 2.2.25  # [win and py2k]
    - udunits2 >=2.2.26,<2.3  # [not (win and py2k)]
    - cftime
    - six

test:
  source_files:
    - cf_units/tests
  requires:
    - pytest
    - pep8
  imports:
    - cf_units
  commands:
    # re-enable the tests when
    # https://github.com/SciTools/cf-units/pull/116 is merged.
    # - cd cf_units && python -m pytest tests

about:
  home: http://www.scitools.org.uk/iris
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Units of measure as required by the Climate and Forecast (CF) metadata conventions.'

extra:
  recipe-maintainers:
    - bjlittle
    - dkillick
    - ocefpaf
    - pelson
